# @package a_model
type: LRest2qp
info:
  n: 2
  k: 1
#  alpha: 0.1   # Alpha is used to to compute a mixture of past and future distribution. alpha=1 ==> the mixture is made of the future alone.
  kernel_type: 'RBF_Kernel'
  kernel_length_scale: 4 # times residuals std
  scale_factor: 1.
  threshold: 0.5